### ISSUE TITLE
Prior sensitivity

### ISSUE THREAD

**Issue by jasonbertram** [hahnlab/CAGEE#12]
Fixed mean k,theta pairs:
[[60.0, 10], [6.0, 100], [0.6, 1000], [0.4, 1500], [0.2, 3000]]

Fixed variance k,theta pairs:
[[96.0, 100], [0.96, 1000], [0.4266666666666667, 1500], [0.10666666666666667, 3000], [0.0096, 10000]]

**Comment by benfulton** [comment]
Long forgotten what this refers to :)
