### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by rresendepinto** [hahnlab/CAGEE#21]
Hi!

I am unable to install CAGEE in my environment. Would it be possible for you to provide a docker image or something like that?

Thank you!

**Comment by benfulton** [comment]
I'll look into it. We don't want to pay to use Docker Hub, but I understand Github can host images now as well.

**Comment by benfulton** [comment]
This is now available at https://github.com/hahnlab/CAGEE/pkgs/container/cagee%2Fcagee . Let me know how it works!
