### ISSUE TITLE
"WARNING: No math library available, calculations may be slow"

### ISSUE THREAD

**Issue by emm-miller** [hahnlab/CAGEE#22]
Hello! I was trying to run CAGEE to estimate a single sigma over the whole tree. I was in the same directory as the below files so they could find them. I ran the command:

`
cagee --tree i.tre --infile i.tab
`

But it gave me the following message along with an empty results folder:

Values converted to LOG space
Read input file i.tab.
Command line: cagee --tree i.tre --infile i.tab 
Discretization range set to 200
WARNING: No math library available, calculations may be slow
Using gamma prior with k=0.375, theta=1600)
Summation probability calculation

Optimizer strategy: Standard Nelder-Mead
Iterations: 300
Expansion: 2
Reflection: 1
Starting Search for Initial Parameter Values
Sigma^2:nan
Segmentation fault

To install CAGEE I ran:
`conda create --name cagee`
`conda activate cagee`
`conda install -n cagee -c bioconda cagee`

These are the packages in my environment:
`
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
cagee                     1.0                  hc5b1d88_0    bioconda
icu                       70.1                 h27087fc_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               16.0.3               h4dfa4b3_0    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
`

Would you have any recommendations? Thank you so much!!

**Comment by benfulton** [comment]
Sorry for leaving this so long. The missing math library shouldn't cause a segmentation fault. I'd guess there's an issue with your input files.
