### ISSUE TITLE
Unknown option: replicate_map

### ISSUE THREAD

**Issue by poojasingh09** [hahnlab/CAGEE#23]
Hi, when I run cagee with a replicate_map I get the following error:
cagee -c gene_oj.cfg  
Unknown option: replicate_map
### this is my gene_oj.cfg file contents:
# Estimate a sigma2 for the given tree and gene transcripts with replicates 
tree = RAxML_bipartitions.all.filt.L.vcf.SNP.gz.recode.mergedOnil.fmiss.raxmlout.T10.clean.CAGE.tre 
infile = gene_tpm_all_samples_onil_OJ.tsv
replicate_map = replicate_map_oj.txt
output_prefix = gene_oj       

### I installed cagee via conda and have v1.0; it seems v1.1 is not available via conda
cagee --version
CAGEE 1.0
                                                                                                        
thanks,

pooja

**Comment by benfulton** [comment]
Replicate maps have not made it into any official release yet. You would have to download the source code and compile it yourself. Do you have a particular interest in this feature?

**Comment by poojasingh09** [comment]
Hi Ben,

I have 5 biological replicates per species, so ideally I wanted to take that variation into account.
Or should I just calculate the species mean across the replicates and use that for CAGEE? 

I tried compiling it from source on a mac and got some errors; will try it again on our linux server.

thanks,

​Pooja

**Comment by benfulton** [comment]
Yes, calculating the species mean is probably the best idea for now. We'll do some more testing on the replicate model and hopefully get it into the next release.
