### ISSUE TITLE
Multiple tissue type output 

### ISSUE THREAD

**Issue by Squigley18** [hahnlab/CAGEE#24]
Hello. 

I have been using CAGEE to look at gene expression across mammalian species (human, macaque, mouse, and cow) using chicken as an outgroup. I am hoping to find genes that are maintained in the mammalian lineage with little/insignificant expression change through evolution and across tissues.  
 I was able to get the code working with one tissue type. I then wanted to incorporate all tissues in my dataset (9 tissue types). The code I ran was: 
```cagee --tree newick.file --infile species.expression.file --sample_group brain --sample_group colon --sample_group heart --sample_group kidney --sample_group liver --sample_group lung --sample_group skeletal --sample_group spleen --sample_group testis```

When I got the output, I noticed that some columns has the same values whereas some had different values. I was wondering if this may be due different expression in different tissue types however there is no way to see which tissue type the gene values are associated with. Is there any way to check this? I tried to alter the transcript name to include tissue type but this then changes all the values; I am unsure what is happening and was hoping to get some advice.  

Along with this I can only seem to get CAGEE to run if I remove the first line of my data. I am not sure the cause of this. 

Thank you for your help in advance! I have added some images of the output I have received in the change.tab file. I also have attached my newick tree and a small subset of my data in case this is of any help. 

Output from CAGEE multiple tissue types: 

![image](https://github.com/hahnlab/CAGEE/assets/84987593/caa193af-047f-4a89-a6f9-e11c7da70054)

Output from CAGEE multiple tissue types, after using grep to extract data for one gene: 
![image](https://github.com/hahnlab/CAGEE/assets/84987593/fed12c90-e22b-4b21-84a2-fa3f19e8cf1c)

 
Output from CAGEE multiple tissue types when changing the transcript name, after using grep to extract data for one gene: 
 
![image](https://github.com/hahnlab/CAGEE/assets/84987593/c3d4f3a0-67e3-4f51-9f79-3801ac754715)

[newick.txt](https://github.com/hahnlab/CAGEE/files/11882556/newick.txt)

[example.dataset.txt](https://github.com/hahnlab/CAGEE/files/11882554/example.dataset.txt)

**Comment by benfulton** [comment]
Hi,

We will release a version soon that shows which sigma^2 value is associated with which sample type, and make sure the sample type field is in the output files as well. 

You need to remove the first line of the dataset, after the header line? What sort of error do you get if you leave it in?

**Comment by Squigley18** [comment]
Hi,
Thank you for letting me know. The error reads as follows:

Using gamma prior with k=0.375, theta=1600)
Summation probability calculation
chicken was not found in transcript ENSG00000198763_brain

**Comment by benfulton** [comment]
@Squigley18 We believe the main branch has fixes now. Are you comfortable with getting the source code and testing it out?

**Comment by Squigley18** [comment]
> @Squigley18 We believe the main branch has fixes now. Are you comfortable with getting the source code and testing it out?

Hi Ben, 

Yes I would be comfortable trying it with the source code. Have you got it uploaded anywhere that I can download from? 

Thank you

**Comment by benfulton** [comment]
You can get it from here:

https://github.com/hahnlab/CAGEE/releases/download/1.1.1.beta/CAGEE1.1.1.beta.tar.gz

Thanks!

**Comment by Squigley18** [comment]
Hi Ben, 

Sorry I haven't had a chance to check until now. I have run the code and it appears to be working well!

 Thank you
