### ISSUE TITLE
replicates in configuration file

### ISSUE THREAD

**Issue by mtswanson2017** [hahnlab/CAGEE#26]
Hi!

Thanks for all of your work on CAGEE! I'm really excited to be using this tool!

I'm able to get cagee to work if I only have a single sample per species. However, when I try to include replicates I get the following error:
Command line: cagee -t primate_pruned.nwk -i full_csn1s1t.tsv 
Discretization range set to 200
Summation probability calculation
Searching for 1 sigmas

Optimizer strategy: Standard Nelder-Mead
Iterations: 300
Expansion: 2
Reflection: 1
Starting Search for Initial Parameter Values
Sigma^2:0.080301
terminate called after throwing an instance of 'std::runtime_error'
  what():  Attempt to access missing probability vector
Aborted (core dumped)

Do you know what I could do to fix this? I've attached my configuration file in case it is formatted incorrectly.

[full_csn1s1t.txt](https://github.com/hahnlab/CAGEE/files/13555008/full_csn1s1t.txt)

**Comment by benfulton** [comment]
Sorry for leaving this so long. You need a replicate map to tell the application which items are considered replicates. The next version of CAGEE will alert to a failed transcript pruning rather than just dump core like that.
